### ISSUE TITLE
ワンショットキャリブレーションの精度検証

### ISSUE THREAD

**Issue by calm0815** [Nishida-Lab/phoxi_ocs#19]
リファクタリングがある程度済んだ後は、今回作ったシステムの精度検証に進まないといけません。

いま現在考えている精度検証についてまとめていきますので、ご意見などございましたらよろしくお願いします。

### **精度検証対象**
キャリブレーションされたロボット座標空間中の作業空間と、実空間上の作業空間の精度

### **精度検証手順**

**実世界側**
1. 産ロボのフランジ面にマーキング用の器具を取り付ける。（針とかペンとか）
2. 作業台の上にマーキング（される）用のボードを載せる。

**シミュレータ側**
3. oneshot_calibrationを起動して、キャリブレーションを行う。
4. キャリブレーションされたロボット座標空間中に作業面を登録する。
5. 登録した作業面上の任意の位置を登録する。
6. 登録した位置に産ロボのフランジ面を上方より近づける。（近づける高さに注意）

**実世界側**
7. 産ロボフランジ面に取り付けた器具が、作業台上に設置されたボードにマーキングするのを確認
8. マーキング位置がシミュレータで指定した位置と合っているかを確認し、キャリブレーションの精度を確認する。

**Comment by calm0815** [comment]
**精度検証するまでのタスク**

- [ ] oneshot_calibrationパッケージの機能整備
- [ ] 修正されたPhoXiカメラの位置から点群を吐き出すシステム構築
- [ ] キャリブレーション済ロボット座標空間上に作業面を登録するシステム構築
- [ ] マーキングボードを含む、実験器具の用意

**Comment by MoriKen254** [comment]
リファクタリングはかなり収束してきていると思います。ぜひ精度検証に進みましょう！

7/11 に登校予定なので、その時お話を聞かせてください。

あと、リファクタリングは軽視されがちですが、プログラミングスキルの向上には欠かせないステップです。純粋に頭の体操にもなるので、機能の実装や思考で煮詰まった時に、やってみてください。プログラミングで培った論理的思考能力は、どんな仕事についた時でも必ず役に立ちます。
（ただ、思考が過ぎて、論理バカ、定義バカにならないようにね笑。世の中矛盾だらけなので、多少のひずみは許容できるように。）

もちろん素早い機能の実装も大切で、それと同時に最低限のリファクタリングができるのも必修科目だと考えています。残念ながら、今大学でそれを学べる機会はそう多いとは言いがたい状況と言わざるを得ないかなと。実問題を解くコードとなればなおさらで、十中八九は手弁当かと思います。

皆さんが今、大学院生としてのソフトウェアのリテラシーを学ばないまま企業に就職し、とんでも論理破綻型スパゲッティソースコードに何ら疑問を抱かない体質にならないようになって欲しいなと願っています。困ったことがあればフォローするので、怖がらずにリファクタリング提案してくださいね。私が issue で指示しなくとも、むず痒くなって勝手に push しちゃうくらいになれば、私の役目は終わりです。

実装＋リファクタリング、ぜひハイブリッドで進めてください。もちろん、楽しみながら！

**Comment by MoriKen254** [comment]
https://github.com/Nishida-Lab/oneshot_calibration_system/issues/1 に移行。

クローズ！
