### ISSUE TITLE
phoxi_img_converter の引っ越し

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/phoxi_ocs#24]
リファクタリング（第一弾）が落ち着いたので、一歩一歩次に行きましょう。

## システム構成

photoneoのテクスチャ画像変換機はどうしてます？ 
AR マーカ検出器はまだ下記リポジトリで独立している？

https://github.com/calm0815/phoxi_img_converter

このあたりのシステム、launch 一発で起動できるようになっていますか?

意図があって分散させているならいいのですが、なんとなく流れ的にこうなったという経緯なら、整理しませんか？

色々まとめてこちらのリポジトリに引っ越しした方が良いと思いますが、いかがでしょう？
すると、`ar_track_alvar` を呼び出すのもここが良いかなと。

その場合、本動作を検証する rosbag ファイルも共有して欲しいなと思います（`/photoneo_center/texture` と、があればあとは一気通貫で動くかな）。

**Comment by calm0815** [comment]
リファクタリングの指導ありがとうございました。
プログラミングの良い勉強になりました。

# システム構成
## phoxi_img_converter
https://github.com/calm0815/phoxi_img_converter
上記リポジトリはおっしゃるとおり独立してます。

## 関連パッケージの整理について
#19 に伴って、phoxi_oscのシステムをPhoXiカメラのbringupシステムの中にまとめてしまおうと考えてます。詳しいシステム構成図があとで @ShunjiroOsada くんから示されると思います。

**Comment by AtsukiYokota** [comment]
これを機にphoxi_cameraに含まれるbringupごと，[phoxi_ros_pkg](https://github.com/Nishida-Lab/phoxi_ros_pkg)に移行しませんか？
[phoxi_camera](https://github.com/Nishida-Lab/phoxi_camera)はforkしてきているかつ本家では機能追加等が現在進行形で進行中という事情もあり，こちらはphoxi本体とのやりとりを担うドライバ的な位置づけとしておいておき，それを外からこちらの都合の良いように呼び出したりする(bringup類)機能や，ワンショットキャリブレーション機能，テクスチャ画像変換機能などはphoxi_ros_pkgにて一元管理したほうが良さそうに思います．

**Comment by calm0815** [comment]
良いと思います。賛成です。

あと、このついでに質問なんですが、
自分のアカウントで管理しているphoxi関連パッケージ（phoxi_img_converter、phoxi_osc）は消しても大丈夫でしょうか。情報漏えいなど気をつける必要があるとおもうので、いつまでもpublicな場所においておくのは良くないかなと心配してます。

**Comment by AtsukiYokota** [comment]
phoxi_img_converterは[phoxi_ros_pkg](https://github.com/Nishida-Lab/phoxi_ros_pkg)に，phoxi_oscはphoxiからは独立したシステムとして[oneshot_calibration_system](https://github.com/Nishida-Lab/oneshot_calibration_system)に引っ越しました．
そのため，個人リポジトリからは消しても大丈夫です.

**Comment by MoriKen254** [comment]
https://github.com/Nishida-Lab/oneshot_calibration_system/issues/2 に移行。

クローズ！
