### ISSUE TITLE
コアダンプ問題

### ISSUE THREAD

**Issue by calm0815** [Nishida-Lab/phoxi_ocs#3]
ar_pose_publisherノードの内部では「複数のTFを受け取った後、PoseArray型に格納してpublishする」という処理を行っています。
このノードを立ち上げたとき、上記処理のPoseArrayに格納する部分でコアダンプを起こします。
（TFの遅延が原因？）

**Comment by MoriKen254** [comment]
お疲れ様です。報告ありがとう。

コアダンプが発生する際の前提条件（環境等）、実行したコマンド（全ターミナル）、ツール等了解していればその現象を確実に再現させる操作順序、ターミナル上のエラーメッセージ（部分でなく）全文を（画像ではなく）テキストで共有して頂けましたら、ここを見ている人が反応しやすくなるかなと思います。

※ なぜこの情報を毎回しつこく聞く背景・一般論・見解については、drop boxで情報共有フォルダに入れているバグ相談の資料をご一読下さい。

**Comment by calm0815** [comment]
レスポンスありがとうございます。
「バグ相談の資料」読ませていただきました。反省する点が多々あり、今後気をつけたいと思います。

以下、改めて問題の整理をします。

### **目的**
以下を機能を満たすノード、ar_pose_publisherノードの開発。

- 複数のARマーカのTFをlistenする。
- 複数のARマーカの位置姿勢情報をgeometry_msgs/PoseArray型に収める。
- 複数のARマーカの情報が収められたPoseArray型をsubscribeする。

### **実行内容**
以下のコマンドを上から順に実行しました。
```
$ roscore
$ rosbag play ~/Dropbox/産ロボ/03_三次元センシング小隊/bag/oneshot_calibration_test.bag -l
$ rosrun phoxi_ocs ar_pose_publisher
```
※ phoxi_ocsは作業ブランチcalm0815/refactoringのものです。。

### **期待動作**
ARマーカの位置姿勢情報がPoseArray型に収まってsubscribeされること

### **発生現象**
テスト用bagファイル再生後、ar_pose_publisherノードを起動すると以下のようになります。

```
kuwano@kuwano-ThinkPad-X1-Carbon-6th:~$ rosrun phoxi_ocs ar_pose_publisher
[ INFO] [1562188618.735328785]: successed !
Segmentation fault (core dumped)
```

### **動作環境**

- OS：ubuntu16.04
- ROS distribution：ROS kinetic
- CPU：i7-8***
- RAM：16GB

**Comment by AtsukiYokota** [comment]
#5 にてPRを出しました．
原因等の詳細はPRをご覧ください．

**Comment by MoriKen254** [comment]
報告＆対応ありがとう！

https://github.com/Nishida-Lab/phoxi_ocs/pull/5
https://github.com/Nishida-Lab/phoxi_ocs/pull/6
にて解決。

クローズ！
