### ISSUE TITLE
定周期でTFをbroadcastする

### ISSUE THREAD

**Issue by AtsukiYokota** [Nishida-Lab/phoxi_ocs#7]
https://github.com/Nishida-Lab/phoxi_ocs/pull/6#issue-294192752 の最後にて言及した内容についてです．

現在，[fixed_phoxi_tf_broadcaster.cpp](https://github.com/Nishida-Lab/phoxi_ocs/blob/master/src/fixed_phoxi_tf_broadcaster.cpp)では，Pose(Stamped)型をサブスクライブして，そのコールバック関数の中でbroadcastしている構成ですが，これだとサブスクライブの周期でbroadcastすることになります．

そうではなく，TFは一定周期（10 Hzが推奨されているようです）でbroadcastする方が好ましいと思います．

**Comment by calm0815** [comment]
この問題って #8 で解決しました？

**Comment by AtsukiYokota** [comment]
してますね、クローズし忘れてました。
クローズ！
